# Generated by Django 4.1 on 2022-08-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'This phone number already exists.'}, max_length=100, null=True, unique=True),
        ),
    ]
